name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

env:
  # Secrets are configured on github.com in repository settings
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    name: Build poster PDF
    runs-on: ubuntu-latest
    container: { image: "aergus/latex" }

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: apt-get update && apt-get install -y inkscape

      - name: Build the thesis
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Poster
          path: "poster.pdf"

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Prepare folder to upload
        run: >-
          mkdir upload &&
          cp poster.pdf upload &&
          echo '{ "redirects": [ { "source": "/", "destination": "/poster.pdf", "permanent": true } ] }' > upload/vercel.json

      - name: Pull Vercel Environment Information
        working-directory: upload
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: upload
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        working-directory: upload
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}